// Code generated by datamaxi-codegen. DO NOT EDIT.

use crate::api::{Client, Config, Datamaxi, Result};
use std::collections::HashMap;
use serde::Deserialize;

// --- Announcements ---

#[derive(Clone)]
pub struct Announcements {
    pub client: Client,
}

impl Datamaxi for Announcements {
    fn new(api_key: String) -> Announcements {
        let config = Config { base_url: None, api_key };
        Announcements { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Announcements {
        let config = Config { base_url: Some(base_url), api_key };
        Announcements { client: Client::new(config) }
    }
}

impl Announcements {
    /// Get latest announcements from centralized exchanges
    pub fn announcements(&self, options: CexAnnouncementsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        if let Some(v) = options.key {
            parameters.insert("key".to_string(), v.to_string());
        }
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.category {
            parameters.insert("category".to_string(), v.to_string());
        }
        self.client.get("/api/v1/cex/announcements", Some(parameters))
    }

}

pub struct CexAnnouncementsOptions {
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub sort: Option<String>,
    pub key: Option<String>,
    pub exchange: Option<String>,
    pub category: Option<String>,
}

impl CexAnnouncementsOptions {
    pub fn new() -> Self {
        CexAnnouncementsOptions {
            page: None,
            limit: None,
            sort: None,
            key: None,
            exchange: None,
            category: None,
        }
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }

    pub fn key(mut self, key: impl Into<String>) -> Self {
        self.key = Some(key.into());
        self
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn category(mut self, category: impl Into<String>) -> Self {
        self.category = Some(category.into());
        self
    }

}

// --- CexCandle ---

#[derive(Clone)]
pub struct CexCandle {
    pub client: Client,
}

impl Datamaxi for CexCandle {
    fn new(api_key: String) -> CexCandle {
        let config = Config { base_url: None, api_key };
        CexCandle { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> CexCandle {
        let config = Config { base_url: Some(base_url), api_key };
        CexCandle { client: Client::new(config) }
    }
}

impl CexCandle {
    /// Get historical candle data for a given `exchange`, `symbol`, `interval` and `market`.
    pub fn get(&self, exchange: impl Into<String>, market: impl Into<String>, symbol: impl Into<String>, options: CexCandleOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("market".to_string(), market.into());
        parameters.insert("symbol".to_string(), symbol.into());
        if let Some(v) = options.currency {
            parameters.insert("currency".to_string(), v.to_string());
        }
        if let Some(v) = options.interval {
            parameters.insert("interval".to_string(), v.to_string());
        }
        if let Some(v) = options.from {
            parameters.insert("from".to_string(), v.to_string());
        }
        if let Some(v) = options.to {
            parameters.insert("to".to_string(), v.to_string());
        }
        self.client.get("/api/v1/cex/candle", Some(parameters))
    }

    /// Get supported exchanges accepted by `/api/v1/cex/candle` endpoint.
    pub fn exchanges(&self, market: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("market".to_string(), market.into());
        self.client.get("/api/v1/cex/candle/exchanges", Some(parameters))
    }

    /// Fetch supported intervals accepted by `/api/v1/cex/candle` endpoint.
    pub fn intervals(&self) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        self.client.get("/api/v1/cex/candle/intervals", None)
    }

    /// Fetch supported symbols accepted by `/api/v1/cex/candle` endpoint.
    pub fn symbols(&self, options: CexCandleSymbolsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        self.client.get("/api/v1/cex/candle/symbols", Some(parameters))
    }

}

pub struct CexCandleOptions {
    pub currency: Option<String>,
    pub interval: Option<String>,
    pub from: Option<String>,
    pub to: Option<String>,
}

impl CexCandleOptions {
    pub fn new() -> Self {
        CexCandleOptions {
            currency: None,
            interval: None,
            from: None,
            to: None,
        }
    }

    pub fn currency(mut self, currency: impl Into<String>) -> Self {
        self.currency = Some(currency.into());
        self
    }

    pub fn interval(mut self, interval: impl Into<String>) -> Self {
        self.interval = Some(interval.into());
        self
    }

    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }

    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }

}

pub struct CexCandleSymbolsOptions {
    pub exchange: Option<String>,
    pub market: Option<String>,
}

impl CexCandleSymbolsOptions {
    pub fn new() -> Self {
        CexCandleSymbolsOptions {
            exchange: None,
            market: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }

}

// --- Dex ---

#[derive(Clone)]
pub struct Dex {
    pub client: Client,
}

impl Datamaxi for Dex {
    fn new(api_key: String) -> Dex {
        let config = Config { base_url: None, api_key };
        Dex { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Dex {
        let config = Config { base_url: Some(base_url), api_key };
        Dex { client: Client::new(config) }
    }
}

impl Dex {
    /// Fetch historical candle data for a given `chain`, `exchange`, `pool` and `interval`.
    pub fn candle(&self, chain: impl Into<String>, exchange: impl Into<String>, pool: impl Into<String>, options: DexCandleOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("chain".to_string(), chain.into());
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("pool".to_string(), pool.into());
        if let Some(v) = options.interval {
            parameters.insert("interval".to_string(), v.to_string());
        }
        if let Some(v) = options.from {
            parameters.insert("from".to_string(), v.to_string());
        }
        if let Some(v) = options.to {
            parameters.insert("to".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        self.client.get("/api/v1/dex/candle", Some(parameters))
    }

    /// Get supported chains accepted by `/api/v1/dex/trade`, `/api/v1/dex/candle` and `/api/v1/dex/liquidity` endpoints.
    pub fn chains(&self) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        self.client.get("/api/v1/dex/chains", None)
    }

    /// Get supported exchanges accepted by `/api/v1/dex/trade`, `/api/v1/dex/candle` and `/api/v1/dex/liquidity` endpoints.
    pub fn exchanges(&self) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        self.client.get("/api/v1/dex/exchanges", None)
    }

    /// Get supported intervals accepted by `/api/v1/dex/candle` endpoint.
    pub fn intervals(&self) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        self.client.get("/api/v1/dex/intervals", None)
    }

    /// Get supported pools accepted by `/api/v1/dex/trade`, `/api/v1/dex/candle` and `/api/v1/dex/liquidity` endpoints.
    pub fn pools(&self, options: DexPoolsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.chain {
            parameters.insert("chain".to_string(), v.to_string());
        }
        self.client.get("/api/v1/dex/pools", Some(parameters))
    }

    /// Get historical DEX trade data for a given `exchange` and `symbol`.
    pub fn trade(&self, chain: impl Into<String>, exchange: impl Into<String>, pool: impl Into<String>, options: DexTradeOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("chain".to_string(), chain.into());
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("pool".to_string(), pool.into());
        if let Some(v) = options.from {
            parameters.insert("from".to_string(), v.to_string());
        }
        if let Some(v) = options.to {
            parameters.insert("to".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        self.client.get("/api/v1/dex/trade", Some(parameters))
    }

}

pub struct DexCandleOptions {
    pub interval: Option<String>,
    pub from: Option<String>,
    pub to: Option<String>,
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub sort: Option<String>,
}

impl DexCandleOptions {
    pub fn new() -> Self {
        DexCandleOptions {
            interval: None,
            from: None,
            to: None,
            page: None,
            limit: None,
            sort: None,
        }
    }

    pub fn interval(mut self, interval: impl Into<String>) -> Self {
        self.interval = Some(interval.into());
        self
    }

    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }

    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }

}

pub struct DexPoolsOptions {
    pub exchange: Option<String>,
    pub chain: Option<String>,
}

impl DexPoolsOptions {
    pub fn new() -> Self {
        DexPoolsOptions {
            exchange: None,
            chain: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn chain(mut self, chain: impl Into<String>) -> Self {
        self.chain = Some(chain.into());
        self
    }

}

pub struct DexTradeOptions {
    pub from: Option<String>,
    pub to: Option<String>,
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub sort: Option<String>,
}

impl DexTradeOptions {
    pub fn new() -> Self {
        DexTradeOptions {
            from: None,
            to: None,
            page: None,
            limit: None,
            sort: None,
        }
    }

    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }

    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }

}

// --- Forex ---

#[derive(Clone)]
pub struct Forex {
    pub client: Client,
}

impl Datamaxi for Forex {
    fn new(api_key: String) -> Forex {
        let config = Config { base_url: None, api_key };
        Forex { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Forex {
        let config = Config { base_url: Some(base_url), api_key };
        Forex { client: Client::new(config) }
    }
}

impl Forex {
    /// Get the latest forex rate for given symbol.
    pub fn get(&self, options: ForexOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.symbol {
            parameters.insert("symbol".to_string(), v.to_string());
        }
        self.client.get("/api/v1/forex", Some(parameters))
    }

    /// Get supported forex symbols.
    pub fn symbols(&self) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        self.client.get("/api/v1/forex/symbols", None)
    }

}

pub struct ForexOptions {
    pub symbol: Option<String>,
}

impl ForexOptions {
    pub fn new() -> Self {
        ForexOptions {
            symbol: None,
        }
    }

    pub fn symbol(mut self, symbol: impl Into<String>) -> Self {
        self.symbol = Some(symbol.into());
        self
    }

}

// --- FundingRate ---

#[derive(Clone)]
pub struct FundingRate {
    pub client: Client,
}

impl Datamaxi for FundingRate {
    fn new(api_key: String) -> FundingRate {
        let config = Config { base_url: None, api_key };
        FundingRate { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> FundingRate {
        let config = Config { base_url: Some(base_url), api_key };
        FundingRate { client: Client::new(config) }
    }
}

impl FundingRate {
    /// Get supported exchanges accepted by `/api/v1/funding-rate` endpoint.
    pub fn exchanges(&self) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        self.client.get("/api/v1/funding-rate/exchanges", None)
    }

    /// Get historical funding rate data for a given `exchange` and `symbol`.
    pub fn history(&self, exchange: impl Into<String>, symbol: impl Into<String>, options: FundingRateHistoryOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("symbol".to_string(), symbol.into());
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.from {
            parameters.insert("from".to_string(), v.to_string());
        }
        if let Some(v) = options.to {
            parameters.insert("to".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        self.client.get("/api/v1/funding-rate/history", Some(parameters))
    }

    /// Fetch the latest funding rate data for a given `exchange` and `symbol`.
    pub fn latest(&self, exchange: impl Into<String>, symbol: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("symbol".to_string(), symbol.into());
        self.client.get("/api/v1/funding-rate/latest", Some(parameters))
    }

    /// Fetch supported symbols accepted by `/api/v1/funding-rate` endpoint.
    pub fn symbols(&self, exchange: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        self.client.get("/api/v1/funding-rate/symbols", Some(parameters))
    }

}

pub struct FundingRateHistoryOptions {
    pub page: Option<String>,
    pub limit: Option<String>,
    pub from: Option<String>,
    pub to: Option<String>,
    pub sort: Option<String>,
}

impl FundingRateHistoryOptions {
    pub fn new() -> Self {
        FundingRateHistoryOptions {
            page: None,
            limit: None,
            from: None,
            to: None,
            sort: None,
        }
    }

    pub fn page(mut self, page: impl Into<String>) -> Self {
        self.page = Some(page.into());
        self
    }

    pub fn limit(mut self, limit: impl Into<String>) -> Self {
        self.limit = Some(limit.into());
        self
    }

    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }

    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }

}

// --- IndexPrice ---

#[derive(Clone)]
pub struct IndexPrice {
    pub client: Client,
}

impl Datamaxi for IndexPrice {
    fn new(api_key: String) -> IndexPrice {
        let config = Config { base_url: None, api_key };
        IndexPrice { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> IndexPrice {
        let config = Config { base_url: Some(base_url), api_key };
        IndexPrice { client: Client::new(config) }
    }
}

impl IndexPrice {
    /// Get index price
    pub fn get(&self, asset: impl Into<String>, options: IndexPriceOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("asset".to_string(), asset.into());
        if let Some(v) = options.from {
            parameters.insert("from".to_string(), v.to_string());
        }
        if let Some(v) = options.to {
            parameters.insert("to".to_string(), v.to_string());
        }
        if let Some(v) = options.interval {
            parameters.insert("interval".to_string(), v.to_string());
        }
        self.client.get("/api/v1/index-price", Some(parameters))
    }

}

pub struct IndexPriceOptions {
    pub from: Option<String>,
    pub to: Option<String>,
    pub interval: Option<String>,
}

impl IndexPriceOptions {
    pub fn new() -> Self {
        IndexPriceOptions {
            from: None,
            to: None,
            interval: None,
        }
    }

    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }

    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }

    pub fn interval(mut self, interval: impl Into<String>) -> Self {
        self.interval = Some(interval.into());
        self
    }

}

// --- Liquidation ---

#[derive(Clone)]
pub struct Liquidation {
    pub client: Client,
}

impl Datamaxi for Liquidation {
    fn new(api_key: String) -> Liquidation {
        let config = Config { base_url: None, api_key };
        Liquidation { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Liquidation {
        let config = Config { base_url: Some(base_url), api_key };
        Liquidation { client: Client::new(config) }
    }
}

impl Liquidation {
    /// Fetch recent liquidation events for a futures symbol on a given exchange, newest first.
    pub fn get(&self, exchange: impl Into<String>, symbol: impl Into<String>, options: LiquidationOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("symbol".to_string(), symbol.into());
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        self.client.get("/api/v1/liquidation", Some(parameters))
    }

}

pub struct LiquidationOptions {
    pub limit: Option<i64>,
}

impl LiquidationOptions {
    pub fn new() -> Self {
        LiquidationOptions {
            limit: None,
        }
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

}

// --- Listing ---

#[derive(Clone)]
pub struct Listing {
    pub client: Client,
}

impl Datamaxi for Listing {
    fn new(api_key: String) -> Listing {
        let config = Config { base_url: None, api_key };
        Listing { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Listing {
        let config = Config { base_url: Some(base_url), api_key };
        Listing { client: Client::new(config) }
    }
}

impl Listing {
    /// Get historical token listings for Upbit and Bithumb for KRW market
    pub fn historical(&self, options: ListingsHistoricalOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.refresh {
            parameters.insert("refresh".to_string(), v.to_string());
        }
        self.client.get("/api/v1/listings/historical", Some(parameters))
    }

}

pub struct ListingsHistoricalOptions {
    pub refresh: Option<bool>,
}

impl ListingsHistoricalOptions {
    pub fn new() -> Self {
        ListingsHistoricalOptions {
            refresh: None,
        }
    }

    pub fn refresh(mut self, refresh: bool) -> Self {
        self.refresh = Some(refresh);
        self
    }

}

// --- MarginBorrow ---

#[derive(Clone)]
pub struct MarginBorrow {
    pub client: Client,
}

impl Datamaxi for MarginBorrow {
    fn new(api_key: String) -> MarginBorrow {
        let config = Config { base_url: None, api_key };
        MarginBorrow { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> MarginBorrow {
        let config = Config { base_url: Some(base_url), api_key };
        MarginBorrow { client: Client::new(config) }
    }
}

impl MarginBorrow {
    /// Get the margin borrow data.
    pub fn get(&self, asset: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("asset".to_string(), asset.into());
        self.client.get("/api/v1/margin-borrow", Some(parameters))
    }

}

// --- NaverTrend ---

#[derive(Clone)]
pub struct NaverTrend {
    pub client: Client,
}

impl Datamaxi for NaverTrend {
    fn new(api_key: String) -> NaverTrend {
        let config = Config { base_url: None, api_key };
        NaverTrend { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> NaverTrend {
        let config = Config { base_url: Some(base_url), api_key };
        NaverTrend { client: Client::new(config) }
    }
}

impl NaverTrend {
    /// Get Naver trend data with a daily frequency for a project that is associated with a given [symbol](./symbols). The values in response are normalized into a range from 0 to 100, where 0 corresponds to a minimum interest, and 100 corresponds to a maximum interest of users in Naver search engine.
    pub fn get(&self, symbol: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("symbol".to_string(), symbol.into());
        self.client.get("/api/v1/naver-trend", Some(parameters))
    }

    /// Get crypto symbols that are accepted by [Naver trend endpoint](./trend).
    pub fn symbols(&self) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        self.client.get("/api/v1/naver-trend/symbols", None)
    }

}

// --- OpenInterest ---

#[derive(Clone)]
pub struct OpenInterest {
    pub client: Client,
}

impl Datamaxi for OpenInterest {
    fn new(api_key: String) -> OpenInterest {
        let config = Config { base_url: None, api_key };
        OpenInterest { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> OpenInterest {
        let config = Config { base_url: Some(base_url), api_key };
        OpenInterest { client: Client::new(config) }
    }
}

impl OpenInterest {
    /// Fetch the most recent Open Interest snapshot for a futures symbol on a given exchange.
    pub fn get(&self, exchange: impl Into<String>, symbol: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("symbol".to_string(), symbol.into());
        self.client.get("/api/v1/open-interest", Some(parameters))
    }

}

// --- Premium ---

#[derive(Clone)]
pub struct Premium {
    pub client: Client,
}

impl Datamaxi for Premium {
    fn new(api_key: String) -> Premium {
        let config = Config { base_url: None, api_key };
        Premium { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Premium {
        let config = Config { base_url: Some(base_url), api_key };
        Premium { client: Client::new(config) }
    }
}

impl Premium {
    /// Get real-time premium (price difference) data across exchanges.
    pub fn get(&self, options: PremiumOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.source_exchange {
            parameters.insert("source_exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.target_exchange {
            parameters.insert("target_exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.asset {
            parameters.insert("asset".to_string(), v.to_string());
        }
        if let Some(v) = options.source_quote {
            parameters.insert("source_quote".to_string(), v.to_string());
        }
        if let Some(v) = options.target_quote {
            parameters.insert("target_quote".to_string(), v.to_string());
        }
        if let Some(v) = options.source_market {
            parameters.insert("source_market".to_string(), v.to_string());
        }
        if let Some(v) = options.target_market {
            parameters.insert("target_market".to_string(), v.to_string());
        }
        if let Some(v) = options.premium_type {
            parameters.insert("premium_type".to_string(), v.to_string());
        }
        if let Some(v) = options.currency {
            parameters.insert("currency".to_string(), v.to_string());
        }
        if let Some(v) = options.conversion_base {
            parameters.insert("conversion_base".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        if let Some(v) = options.key {
            parameters.insert("key".to_string(), v.to_string());
        }
        if let Some(v) = options.query {
            parameters.insert("query".to_string(), v.to_string());
        }
        if let Some(v) = options.only_transferable {
            parameters.insert("only_transferable".to_string(), v.to_string());
        }
        if let Some(v) = options.network {
            parameters.insert("network".to_string(), v.to_string());
        }
        if let Some(v) = options.min_sv {
            parameters.insert("min_sv".to_string(), v.to_string());
        }
        if let Some(v) = options.min_tv {
            parameters.insert("min_tv".to_string(), v.to_string());
        }
        self.client.get("/api/v1/premium", Some(parameters))
    }

    /// Get supported source exchanges for premium data.
    pub fn exchanges(&self) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        self.client.get("/api/v1/premium/exchanges", None)
    }

}

pub struct PremiumOptions {
    pub source_exchange: Option<String>,
    pub target_exchange: Option<String>,
    pub asset: Option<String>,
    pub source_quote: Option<String>,
    pub target_quote: Option<String>,
    pub source_market: Option<String>,
    pub target_market: Option<String>,
    pub premium_type: Option<String>,
    pub currency: Option<String>,
    pub conversion_base: Option<String>,
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub sort: Option<String>,
    pub key: Option<String>,
    pub query: Option<String>,
    pub only_transferable: Option<bool>,
    pub network: Option<String>,
    pub min_sv: Option<f64>,
    pub min_tv: Option<f64>,
}

impl PremiumOptions {
    pub fn new() -> Self {
        PremiumOptions {
            source_exchange: None,
            target_exchange: None,
            asset: None,
            source_quote: None,
            target_quote: None,
            source_market: None,
            target_market: None,
            premium_type: None,
            currency: None,
            conversion_base: None,
            page: None,
            limit: None,
            sort: None,
            key: None,
            query: None,
            only_transferable: None,
            network: None,
            min_sv: None,
            min_tv: None,
        }
    }

    pub fn source_exchange(mut self, source_exchange: impl Into<String>) -> Self {
        self.source_exchange = Some(source_exchange.into());
        self
    }

    pub fn target_exchange(mut self, target_exchange: impl Into<String>) -> Self {
        self.target_exchange = Some(target_exchange.into());
        self
    }

    pub fn asset(mut self, asset: impl Into<String>) -> Self {
        self.asset = Some(asset.into());
        self
    }

    pub fn source_quote(mut self, source_quote: impl Into<String>) -> Self {
        self.source_quote = Some(source_quote.into());
        self
    }

    pub fn target_quote(mut self, target_quote: impl Into<String>) -> Self {
        self.target_quote = Some(target_quote.into());
        self
    }

    pub fn source_market(mut self, source_market: impl Into<String>) -> Self {
        self.source_market = Some(source_market.into());
        self
    }

    pub fn target_market(mut self, target_market: impl Into<String>) -> Self {
        self.target_market = Some(target_market.into());
        self
    }

    pub fn premium_type(mut self, premium_type: impl Into<String>) -> Self {
        self.premium_type = Some(premium_type.into());
        self
    }

    pub fn currency(mut self, currency: impl Into<String>) -> Self {
        self.currency = Some(currency.into());
        self
    }

    pub fn conversion_base(mut self, conversion_base: impl Into<String>) -> Self {
        self.conversion_base = Some(conversion_base.into());
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }

    pub fn key(mut self, key: impl Into<String>) -> Self {
        self.key = Some(key.into());
        self
    }

    pub fn query(mut self, query: impl Into<String>) -> Self {
        self.query = Some(query.into());
        self
    }

    pub fn only_transferable(mut self, only_transferable: bool) -> Self {
        self.only_transferable = Some(only_transferable);
        self
    }

    pub fn network(mut self, network: impl Into<String>) -> Self {
        self.network = Some(network.into());
        self
    }

    pub fn min_sv(mut self, min_sv: f64) -> Self {
        self.min_sv = Some(min_sv);
        self
    }

    pub fn min_tv(mut self, min_tv: f64) -> Self {
        self.min_tv = Some(min_tv);
        self
    }

}

// --- Telegram ---

#[derive(Clone)]
pub struct Telegram {
    pub client: Client,
}

impl Datamaxi for Telegram {
    fn new(api_key: String) -> Telegram {
        let config = Config { base_url: None, api_key };
        Telegram { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Telegram {
        let config = Config { base_url: Some(base_url), api_key };
        Telegram { client: Client::new(config) }
    }
}

impl Telegram {
    /// Get Telegram channels
    pub fn channels(&self, options: TelegramChannelsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.category {
            parameters.insert("category".to_string(), v.to_string());
        }
        if let Some(v) = options.key {
            parameters.insert("key".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        self.client.get("/api/v1/telegram/channels", Some(parameters))
    }

    /// Get Telegram messages.
    pub fn messages(&self, options: TelegramMessagesOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.channel {
            parameters.insert("channel".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.key {
            parameters.insert("key".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        if let Some(v) = options.category {
            parameters.insert("category".to_string(), v.to_string());
        }
        if let Some(v) = options.search_query {
            parameters.insert("search_query".to_string(), v.to_string());
        }
        self.client.get("/api/v1/telegram/messages", Some(parameters))
    }

}

pub struct TelegramChannelsOptions {
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub category: Option<String>,
    pub key: Option<String>,
    pub sort: Option<String>,
}

impl TelegramChannelsOptions {
    pub fn new() -> Self {
        TelegramChannelsOptions {
            page: None,
            limit: None,
            category: None,
            key: None,
            sort: None,
        }
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn category(mut self, category: impl Into<String>) -> Self {
        self.category = Some(category.into());
        self
    }

    pub fn key(mut self, key: impl Into<String>) -> Self {
        self.key = Some(key.into());
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }

}

pub struct TelegramMessagesOptions {
    pub channel: Option<String>,
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub key: Option<String>,
    pub sort: Option<String>,
    pub category: Option<String>,
    pub search_query: Option<String>,
}

impl TelegramMessagesOptions {
    pub fn new() -> Self {
        TelegramMessagesOptions {
            channel: None,
            page: None,
            limit: None,
            key: None,
            sort: None,
            category: None,
            search_query: None,
        }
    }

    pub fn channel(mut self, channel: impl Into<String>) -> Self {
        self.channel = Some(channel.into());
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn key(mut self, key: impl Into<String>) -> Self {
        self.key = Some(key.into());
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }

    pub fn category(mut self, category: impl Into<String>) -> Self {
        self.category = Some(category.into());
        self
    }

    pub fn search_query(mut self, search_query: impl Into<String>) -> Self {
        self.search_query = Some(search_query.into());
        self
    }

}

// --- Ticker ---

#[derive(Clone)]
pub struct Ticker {
    pub client: Client,
}

impl Datamaxi for Ticker {
    fn new(api_key: String) -> Ticker {
        let config = Config { base_url: None, api_key };
        Ticker { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Ticker {
        let config = Config { base_url: Some(base_url), api_key };
        Ticker { client: Client::new(config) }
    }
}

impl Ticker {
    /// Fetch the latest ticker for symbol from given exchange.
    pub fn get(&self, exchange: impl Into<String>, symbol: impl Into<String>, options: TickerOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("symbol".to_string(), symbol.into());
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        if let Some(v) = options.currency {
            parameters.insert("currency".to_string(), v.to_string());
        }
        if let Some(v) = options.conversion_base {
            parameters.insert("conversion_base".to_string(), v.to_string());
        }
        self.client.get("/api/v1/ticker", Some(parameters))
    }

    /// Get supported exchanges accepted by `/api/v1/ticker` endpoint.
    pub fn exchanges(&self, options: TickerExchangesOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        self.client.get("/api/v1/ticker/exchanges", Some(parameters))
    }

    /// Get supported symbols accepted by `/api/v1/ticker` endpoint.
    pub fn symbols(&self, exchange: impl Into<String>, options: TickerSymbolsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        self.client.get("/api/v1/ticker/symbols", Some(parameters))
    }

}

pub struct TickerOptions {
    pub market: Option<String>,
    pub currency: Option<String>,
    pub conversion_base: Option<String>,
}

impl TickerOptions {
    pub fn new() -> Self {
        TickerOptions {
            market: None,
            currency: None,
            conversion_base: None,
        }
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }

    pub fn currency(mut self, currency: impl Into<String>) -> Self {
        self.currency = Some(currency.into());
        self
    }

    pub fn conversion_base(mut self, conversion_base: impl Into<String>) -> Self {
        self.conversion_base = Some(conversion_base.into());
        self
    }

}

pub struct TickerExchangesOptions {
    pub market: Option<String>,
}

impl TickerExchangesOptions {
    pub fn new() -> Self {
        TickerExchangesOptions {
            market: None,
        }
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }

}

pub struct TickerSymbolsOptions {
    pub market: Option<String>,
}

impl TickerSymbolsOptions {
    pub fn new() -> Self {
        TickerSymbolsOptions {
            market: None,
        }
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }

}

// --- Token ---

#[derive(Clone)]
pub struct Token {
    pub client: Client,
}

impl Datamaxi for Token {
    fn new(api_key: String) -> Token {
        let config = Config { base_url: None, api_key };
        Token { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Token {
        let config = Config { base_url: Some(base_url), api_key };
        Token { client: Client::new(config) }
    }
}

impl Token {
    /// Fetch latest token updates
    pub fn updates(&self, options: CexTokenUpdatesOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.type {
            parameters.insert("type".to_string(), v.to_string());
        }
        self.client.get("/api/v1/cex/token/updates", Some(parameters))
    }

}

pub struct CexTokenUpdatesOptions {
    pub page: Option<String>,
    pub limit: Option<String>,
    pub type: Option<String>,
}

impl CexTokenUpdatesOptions {
    pub fn new() -> Self {
        CexTokenUpdatesOptions {
            page: None,
            limit: None,
            type: None,
        }
    }

    pub fn page(mut self, page: impl Into<String>) -> Self {
        self.page = Some(page.into());
        self
    }

    pub fn limit(mut self, limit: impl Into<String>) -> Self {
        self.limit = Some(limit.into());
        self
    }

    pub fn type(mut self, type: impl Into<String>) -> Self {
        self.type = Some(type.into());
        self
    }

}

// --- TradingFees ---

#[derive(Clone)]
pub struct TradingFees {
    pub client: Client,
}

impl Datamaxi for TradingFees {
    fn new(api_key: String) -> TradingFees {
        let config = Config { base_url: None, api_key };
        TradingFees { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> TradingFees {
        let config = Config { base_url: Some(base_url), api_key };
        TradingFees { client: Client::new(config) }
    }
}

impl TradingFees {
    /// Get trading fees.
    pub fn fees(&self, options: CexFeesOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.symbol {
            parameters.insert("symbol".to_string(), v.to_string());
        }
        self.client.get("/api/v1/cex/fees", Some(parameters))
    }

    /// Get supported exchanges accepted by `/api/v1/trading-fees` endpoint.
    pub fn exchanges(&self) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        self.client.get("/api/v1/cex/fees/exchanges", None)
    }

    /// Get supported symbols accepted by `/api/v1/trading-fees` endpoint.
    pub fn symbols(&self, exchange: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        self.client.get("/api/v1/cex/fees/symbols", Some(parameters))
    }

}

pub struct CexFeesOptions {
    pub exchange: Option<String>,
    pub symbol: Option<String>,
}

impl CexFeesOptions {
    pub fn new() -> Self {
        CexFeesOptions {
            exchange: None,
            symbol: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn symbol(mut self, symbol: impl Into<String>) -> Self {
        self.symbol = Some(symbol.into());
        self
    }

}

// --- WalletStatus ---

#[derive(Clone)]
pub struct WalletStatus {
    pub client: Client,
}

impl Datamaxi for WalletStatus {
    fn new(api_key: String) -> WalletStatus {
        let config = Config { base_url: None, api_key };
        WalletStatus { client: Client::new(config) }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> WalletStatus {
        let config = Config { base_url: Some(base_url), api_key };
        WalletStatus { client: Client::new(config) }
    }
}

impl WalletStatus {
    /// Get the latest wallet status for asset from given exchange.
    pub fn get(&self, asset: impl Into<String>, options: WalletStatusOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("asset".to_string(), asset.into());
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        self.client.get("/api/v1/wallet-status", Some(parameters))
    }

    /// Get assets accepted by `/api/v1/wallet-status` endpoint.
    pub fn assets(&self, exchange: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        self.client.get("/api/v1/wallet-status/assets", Some(parameters))
    }

    /// Get exchanges accepted by `/api/v1/wallet-status` endpoint.
    pub fn exchanges(&self) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        self.client.get("/api/v1/wallet-status/exchanges", None)
    }

}

pub struct WalletStatusOptions {
    pub exchange: Option<String>,
}

impl WalletStatusOptions {
    pub fn new() -> Self {
        WalletStatusOptions {
            exchange: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

}
