// Code generated by datamaxi-codegen. DO NOT EDIT.

use crate::api::{Client, Config, Datamaxi, Result};
use serde::Deserialize;
use std::collections::HashMap;

// --- Announcements ---

#[derive(Clone)]
pub struct Announcements {
    pub client: Client,
}

impl Datamaxi for Announcements {
    fn new(api_key: String) -> Announcements {
        let config = Config {
            base_url: None,
            api_key,
        };
        Announcements {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Announcements {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        Announcements {
            client: Client::new(config),
        }
    }
}

impl Announcements {
    /// Get latest announcements from centralized exchanges
    pub fn announcements(&self, options: CexAnnouncementsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        if let Some(v) = options.key {
            parameters.insert("key".to_string(), v.to_string());
        }
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.category {
            parameters.insert("category".to_string(), v.to_string());
        }
        self.client.get("/cex/announcements", Some(parameters))
    }
}

pub struct CexAnnouncementsOptions {
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub sort: Option<String>,
    pub key: Option<String>,
    pub exchange: Option<String>,
    pub category: Option<String>,
}

impl CexAnnouncementsOptions {
    pub fn new() -> Self {
        CexAnnouncementsOptions {
            page: None,
            limit: None,
            sort: None,
            key: None,
            exchange: None,
            category: None,
        }
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }

    pub fn key(mut self, key: impl Into<String>) -> Self {
        self.key = Some(key.into());
        self
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn category(mut self, category: impl Into<String>) -> Self {
        self.category = Some(category.into());
        self
    }
}

// --- CexCandle ---

#[derive(Clone)]
pub struct CexCandle {
    pub client: Client,
}

impl Datamaxi for CexCandle {
    fn new(api_key: String) -> CexCandle {
        let config = Config {
            base_url: None,
            api_key,
        };
        CexCandle {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> CexCandle {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        CexCandle {
            client: Client::new(config),
        }
    }
}

impl CexCandle {
    /// Get historical candle data for a given `exchange`, `symbol`, `interval` and `market`.
    pub fn get(
        &self,
        exchange: impl Into<String>,
        market: impl Into<String>,
        symbol: impl Into<String>,
        options: CexCandleOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("market".to_string(), market.into());
        parameters.insert("symbol".to_string(), symbol.into());
        if let Some(v) = options.currency {
            parameters.insert("currency".to_string(), v.to_string());
        }
        if let Some(v) = options.interval {
            parameters.insert("interval".to_string(), v.to_string());
        }
        if let Some(v) = options.from {
            parameters.insert("from".to_string(), v.to_string());
        }
        if let Some(v) = options.to {
            parameters.insert("to".to_string(), v.to_string());
        }
        self.client.get("/cex/candle", Some(parameters))
    }

    /// Get supported exchanges accepted by `/api/v1/cex/candle` endpoint.
    pub fn exchanges(&self, market: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("market".to_string(), market.into());
        self.client.get("/cex/candle/exchanges", Some(parameters))
    }

    /// Fetch supported intervals accepted by `/api/v1/cex/candle` endpoint.
    pub fn intervals(&self) -> Result<serde_json::Value> {
        self.client.get("/cex/candle/intervals", None)
    }

    /// Fetch supported symbols accepted by `/api/v1/cex/candle` endpoint.
    pub fn symbols(&self, options: CexCandleSymbolsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        self.client.get("/cex/candle/symbols", Some(parameters))
    }
}

pub struct CexCandleOptions {
    pub currency: Option<String>,
    pub interval: Option<String>,
    pub from: Option<String>,
    pub to: Option<String>,
}

impl CexCandleOptions {
    pub fn new() -> Self {
        CexCandleOptions {
            currency: None,
            interval: None,
            from: None,
            to: None,
        }
    }

    pub fn currency(mut self, currency: impl Into<String>) -> Self {
        self.currency = Some(currency.into());
        self
    }

    pub fn interval(mut self, interval: impl Into<String>) -> Self {
        self.interval = Some(interval.into());
        self
    }

    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }

    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }
}

pub struct CexCandleSymbolsOptions {
    pub exchange: Option<String>,
    pub market: Option<String>,
}

impl CexCandleSymbolsOptions {
    pub fn new() -> Self {
        CexCandleSymbolsOptions {
            exchange: None,
            market: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }
}

// --- CexSymbol ---

#[derive(Clone)]
pub struct CexSymbol {
    pub client: Client,
}

impl Datamaxi for CexSymbol {
    fn new(api_key: String) -> CexSymbol {
        let config = Config {
            base_url: None,
            api_key,
        };
        CexSymbol {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> CexSymbol {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        CexSymbol {
            client: Client::new(config),
        }
    }
}

impl CexSymbol {
    /// Return currently-active caution/warning/danger flagged symbols. Bithumb provides an expiry (end_at); other exchanges are open-ended until the next collector poll clears them.
    pub fn cautions(&self, options: CexSymbolCautionsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        if let Some(v) = options.min_level {
            parameters.insert("min_level".to_string(), v.to_string());
        }
        if let Some(v) = options.active_only {
            parameters.insert("active_only".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        self.client.get("/cex/symbol/cautions", Some(parameters))
    }

    /// Return symbols with a known delisting_at timestamp or trading_status in {delisting, delisted}. Filter by time window to get upcoming delistings.
    pub fn delistings(&self, options: CexSymbolDelistingsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        if let Some(v) = options.from_ms {
            parameters.insert("from_ms".to_string(), v.to_string());
        }
        if let Some(v) = options.to_ms {
            parameters.insert("to_ms".to_string(), v.to_string());
        }
        if let Some(v) = options.include_past {
            parameters.insert("include_past".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        self.client.get("/cex/symbol/delistings", Some(parameters))
    }

    /// Sums long/short liquidation volume across all events in a rolling window for every exchange × quote pairing of the base asset. Window max 30d; default 24h.
    pub fn liquidation(
        &self,
        base: impl Into<String>,
        options: CexSymbolLiquidationOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("base".to_string(), base.into());
        if let Some(v) = options.window {
            parameters.insert("window".to_string(), v.to_string());
        }
        self.client.get("/cex/symbol/liquidation", Some(parameters))
    }

    /// Fetch per-symbol trading status, caution flags, tags and timing metadata collected by tfsymbolmeta.
    pub fn metadata(&self, options: CexSymbolMetadataOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        if let Some(v) = options.base {
            parameters.insert("base".to_string(), v.to_string());
        }
        if let Some(v) = options.quote {
            parameters.insert("quote".to_string(), v.to_string());
        }
        if let Some(v) = options.status {
            parameters.insert("status".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        self.client.get("/cex/symbol/metadata", Some(parameters))
    }

    /// Latest Open Interest snapshot across every futures venue carrying the given base. Sorted by USD value descending, NULLs last.
    pub fn oi(
        &self,
        base: impl Into<String>,
        options: CexSymbolOiOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("base".to_string(), base.into());
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        self.client.get("/cex/symbol/oi", Some(parameters))
    }

    /// Enriched snapshot combining the latest OI (USD) with 1h/4h/24h change percentages and OI/24h volume ratio. Backed by the tfopeninterest taskflow's Redis HASH.
    pub fn oi_stats(
        &self,
        base: impl Into<String>,
        options: CexSymbolOiStatsOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("base".to_string(), base.into());
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.currency {
            parameters.insert("currency".to_string(), v.to_string());
        }
        self.client.get("/cex/symbol/oi-stats", Some(parameters))
    }

    /// Fetch (exchange, market, base, quote, tag) rows from cex_symbol_tag. Use to find every symbol flagged with a given tag (e.g. all meme coins across exchanges).
    pub fn tags(&self, options: CexSymbolTagsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.tag {
            parameters.insert("tag".to_string(), v.to_string());
        }
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        if let Some(v) = options.base {
            parameters.insert("base".to_string(), v.to_string());
        }
        if let Some(v) = options.source {
            parameters.insert("source".to_string(), v.to_string());
        }
        if let Some(v) = options.min_confidence {
            parameters.insert("min_confidence".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        self.client.get("/cex/symbol/tags", Some(parameters))
    }

    /// Latest 24h trading volume across every (exchange, market, quote) a token lists on. Backed by cache.latest_volume.
    pub fn volume(
        &self,
        base: impl Into<String>,
        options: CexSymbolVolumeOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("base".to_string(), base.into());
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        self.client.get("/cex/symbol/volume", Some(parameters))
    }
}

pub struct CexSymbolCautionsOptions {
    pub exchange: Option<String>,
    pub market: Option<String>,
    pub min_level: Option<String>,
    pub active_only: Option<bool>,
    pub limit: Option<i64>,
    pub page: Option<i64>,
}

impl CexSymbolCautionsOptions {
    pub fn new() -> Self {
        CexSymbolCautionsOptions {
            exchange: None,
            market: None,
            min_level: None,
            active_only: None,
            limit: None,
            page: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }

    pub fn min_level(mut self, min_level: impl Into<String>) -> Self {
        self.min_level = Some(min_level.into());
        self
    }

    pub fn active_only(mut self, active_only: bool) -> Self {
        self.active_only = Some(active_only);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }
}

pub struct CexSymbolDelistingsOptions {
    pub exchange: Option<String>,
    pub market: Option<String>,
    pub from_ms: Option<i64>,
    pub to_ms: Option<i64>,
    pub include_past: Option<bool>,
    pub limit: Option<i64>,
    pub page: Option<i64>,
}

impl CexSymbolDelistingsOptions {
    pub fn new() -> Self {
        CexSymbolDelistingsOptions {
            exchange: None,
            market: None,
            from_ms: None,
            to_ms: None,
            include_past: None,
            limit: None,
            page: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }

    pub fn from_ms(mut self, from_ms: i64) -> Self {
        self.from_ms = Some(from_ms);
        self
    }

    pub fn to_ms(mut self, to_ms: i64) -> Self {
        self.to_ms = Some(to_ms);
        self
    }

    pub fn include_past(mut self, include_past: bool) -> Self {
        self.include_past = Some(include_past);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }
}

pub struct CexSymbolLiquidationOptions {
    pub window: Option<String>,
}

impl CexSymbolLiquidationOptions {
    pub fn new() -> Self {
        CexSymbolLiquidationOptions { window: None }
    }

    pub fn window(mut self, window: impl Into<String>) -> Self {
        self.window = Some(window.into());
        self
    }
}

pub struct CexSymbolMetadataOptions {
    pub exchange: Option<String>,
    pub market: Option<String>,
    pub base: Option<String>,
    pub quote: Option<String>,
    pub status: Option<String>,
    pub limit: Option<i64>,
    pub page: Option<i64>,
}

impl CexSymbolMetadataOptions {
    pub fn new() -> Self {
        CexSymbolMetadataOptions {
            exchange: None,
            market: None,
            base: None,
            quote: None,
            status: None,
            limit: None,
            page: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }

    pub fn base(mut self, base: impl Into<String>) -> Self {
        self.base = Some(base.into());
        self
    }

    pub fn quote(mut self, quote: impl Into<String>) -> Self {
        self.quote = Some(quote.into());
        self
    }

    pub fn status(mut self, status: impl Into<String>) -> Self {
        self.status = Some(status.into());
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }
}

pub struct CexSymbolOiOptions {
    pub exchange: Option<String>,
}

impl CexSymbolOiOptions {
    pub fn new() -> Self {
        CexSymbolOiOptions { exchange: None }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }
}

pub struct CexSymbolOiStatsOptions {
    pub exchange: Option<String>,
    pub currency: Option<String>,
}

impl CexSymbolOiStatsOptions {
    pub fn new() -> Self {
        CexSymbolOiStatsOptions {
            exchange: None,
            currency: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn currency(mut self, currency: impl Into<String>) -> Self {
        self.currency = Some(currency.into());
        self
    }
}

pub struct CexSymbolTagsOptions {
    pub tag: Option<String>,
    pub exchange: Option<String>,
    pub market: Option<String>,
    pub base: Option<String>,
    pub source: Option<String>,
    pub min_confidence: Option<i64>,
    pub limit: Option<i64>,
    pub page: Option<i64>,
}

impl CexSymbolTagsOptions {
    pub fn new() -> Self {
        CexSymbolTagsOptions {
            tag: None,
            exchange: None,
            market: None,
            base: None,
            source: None,
            min_confidence: None,
            limit: None,
            page: None,
        }
    }

    pub fn tag(mut self, tag: impl Into<String>) -> Self {
        self.tag = Some(tag.into());
        self
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }

    pub fn base(mut self, base: impl Into<String>) -> Self {
        self.base = Some(base.into());
        self
    }

    pub fn source(mut self, source: impl Into<String>) -> Self {
        self.source = Some(source.into());
        self
    }

    pub fn min_confidence(mut self, min_confidence: i64) -> Self {
        self.min_confidence = Some(min_confidence);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }
}

pub struct CexSymbolVolumeOptions {
    pub market: Option<String>,
}

impl CexSymbolVolumeOptions {
    pub fn new() -> Self {
        CexSymbolVolumeOptions { market: None }
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }
}

// --- Dex ---

#[derive(Clone)]
pub struct Dex {
    pub client: Client,
}

impl Datamaxi for Dex {
    fn new(api_key: String) -> Dex {
        let config = Config {
            base_url: None,
            api_key,
        };
        Dex {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Dex {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        Dex {
            client: Client::new(config),
        }
    }
}

impl Dex {
    /// Fetch historical candle data for a given `chain`, `exchange`, `pool` and `interval`.
    pub fn candle(
        &self,
        chain: impl Into<String>,
        exchange: impl Into<String>,
        pool: impl Into<String>,
        options: DexCandleOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("chain".to_string(), chain.into());
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("pool".to_string(), pool.into());
        if let Some(v) = options.interval {
            parameters.insert("interval".to_string(), v.to_string());
        }
        if let Some(v) = options.from {
            parameters.insert("from".to_string(), v.to_string());
        }
        if let Some(v) = options.to {
            parameters.insert("to".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        self.client.get("/dex/candle", Some(parameters))
    }

    /// Get supported chains accepted by `/api/v1/dex/trade`, `/api/v1/dex/candle` and `/api/v1/dex/liquidity` endpoints.
    pub fn chains(&self) -> Result<serde_json::Value> {
        self.client.get("/dex/chains", None)
    }

    /// Get supported exchanges accepted by `/api/v1/dex/trade`, `/api/v1/dex/candle` and `/api/v1/dex/liquidity` endpoints.
    pub fn exchanges(&self) -> Result<serde_json::Value> {
        self.client.get("/dex/exchanges", None)
    }

    /// Get supported intervals accepted by `/api/v1/dex/candle` endpoint.
    pub fn intervals(&self) -> Result<serde_json::Value> {
        self.client.get("/dex/intervals", None)
    }

    /// Get supported pools accepted by `/api/v1/dex/trade`, `/api/v1/dex/candle` and `/api/v1/dex/liquidity` endpoints.
    pub fn pools(&self, options: DexPoolsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.chain {
            parameters.insert("chain".to_string(), v.to_string());
        }
        self.client.get("/dex/pools", Some(parameters))
    }

    /// Get historical DEX trade data for a given `exchange` and `symbol`.
    pub fn trade(
        &self,
        chain: impl Into<String>,
        exchange: impl Into<String>,
        pool: impl Into<String>,
        options: DexTradeOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("chain".to_string(), chain.into());
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("pool".to_string(), pool.into());
        if let Some(v) = options.from {
            parameters.insert("from".to_string(), v.to_string());
        }
        if let Some(v) = options.to {
            parameters.insert("to".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        self.client.get("/dex/trade", Some(parameters))
    }
}

pub struct DexCandleOptions {
    pub interval: Option<String>,
    pub from: Option<String>,
    pub to: Option<String>,
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub sort: Option<String>,
}

impl DexCandleOptions {
    pub fn new() -> Self {
        DexCandleOptions {
            interval: None,
            from: None,
            to: None,
            page: None,
            limit: None,
            sort: None,
        }
    }

    pub fn interval(mut self, interval: impl Into<String>) -> Self {
        self.interval = Some(interval.into());
        self
    }

    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }

    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }
}

pub struct DexPoolsOptions {
    pub exchange: Option<String>,
    pub chain: Option<String>,
}

impl DexPoolsOptions {
    pub fn new() -> Self {
        DexPoolsOptions {
            exchange: None,
            chain: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn chain(mut self, chain: impl Into<String>) -> Self {
        self.chain = Some(chain.into());
        self
    }
}

pub struct DexTradeOptions {
    pub from: Option<String>,
    pub to: Option<String>,
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub sort: Option<String>,
}

impl DexTradeOptions {
    pub fn new() -> Self {
        DexTradeOptions {
            from: None,
            to: None,
            page: None,
            limit: None,
            sort: None,
        }
    }

    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }

    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }
}

// --- Forex ---

#[derive(Clone)]
pub struct Forex {
    pub client: Client,
}

impl Datamaxi for Forex {
    fn new(api_key: String) -> Forex {
        let config = Config {
            base_url: None,
            api_key,
        };
        Forex {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Forex {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        Forex {
            client: Client::new(config),
        }
    }
}

impl Forex {
    /// Get the latest forex rate for given symbol.
    pub fn get(&self, options: ForexOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.symbol {
            parameters.insert("symbol".to_string(), v.to_string());
        }
        self.client.get("/forex", Some(parameters))
    }

    /// Get supported forex symbols.
    pub fn symbols(&self) -> Result<serde_json::Value> {
        self.client.get("/forex/symbols", None)
    }
}

pub struct ForexOptions {
    pub symbol: Option<String>,
}

impl ForexOptions {
    pub fn new() -> Self {
        ForexOptions { symbol: None }
    }

    pub fn symbol(mut self, symbol: impl Into<String>) -> Self {
        self.symbol = Some(symbol.into());
        self
    }
}

// --- FundingRate ---

#[derive(Clone)]
pub struct FundingRate {
    pub client: Client,
}

impl Datamaxi for FundingRate {
    fn new(api_key: String) -> FundingRate {
        let config = Config {
            base_url: None,
            api_key,
        };
        FundingRate {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> FundingRate {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        FundingRate {
            client: Client::new(config),
        }
    }
}

impl FundingRate {
    /// Get supported exchanges accepted by `/api/v1/funding-rate` endpoint.
    pub fn exchanges(&self) -> Result<serde_json::Value> {
        self.client.get("/funding-rate/exchanges", None)
    }

    /// Get historical funding rate data for a given `exchange` and `symbol`.
    pub fn history(
        &self,
        exchange: impl Into<String>,
        symbol: impl Into<String>,
        options: FundingRateHistoryOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("symbol".to_string(), symbol.into());
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.from {
            parameters.insert("from".to_string(), v.to_string());
        }
        if let Some(v) = options.to {
            parameters.insert("to".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        self.client.get("/funding-rate/history", Some(parameters))
    }

    /// Fetch the latest funding rate data for a given `exchange` and `symbol`.
    pub fn latest(
        &self,
        exchange: impl Into<String>,
        symbol: impl Into<String>,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("symbol".to_string(), symbol.into());
        self.client.get("/funding-rate/latest", Some(parameters))
    }

    /// Fetch supported symbols accepted by `/api/v1/funding-rate` endpoint.
    pub fn symbols(&self, options: FundingRateSymbolsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        self.client.get("/funding-rate/symbols", Some(parameters))
    }
}

pub struct FundingRateHistoryOptions {
    pub page: Option<String>,
    pub limit: Option<String>,
    pub from: Option<String>,
    pub to: Option<String>,
    pub sort: Option<String>,
}

impl FundingRateHistoryOptions {
    pub fn new() -> Self {
        FundingRateHistoryOptions {
            page: None,
            limit: None,
            from: None,
            to: None,
            sort: None,
        }
    }

    pub fn page(mut self, page: impl Into<String>) -> Self {
        self.page = Some(page.into());
        self
    }

    pub fn limit(mut self, limit: impl Into<String>) -> Self {
        self.limit = Some(limit.into());
        self
    }

    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }

    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }
}

pub struct FundingRateSymbolsOptions {
    pub exchange: Option<String>,
}

impl FundingRateSymbolsOptions {
    pub fn new() -> Self {
        FundingRateSymbolsOptions { exchange: None }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }
}

// --- IndexPrice ---

#[derive(Clone)]
pub struct IndexPrice {
    pub client: Client,
}

impl Datamaxi for IndexPrice {
    fn new(api_key: String) -> IndexPrice {
        let config = Config {
            base_url: None,
            api_key,
        };
        IndexPrice {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> IndexPrice {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        IndexPrice {
            client: Client::new(config),
        }
    }
}

impl IndexPrice {
    /// Get index price
    pub fn get(
        &self,
        asset: impl Into<String>,
        options: IndexPriceOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("asset".to_string(), asset.into());
        if let Some(v) = options.from {
            parameters.insert("from".to_string(), v.to_string());
        }
        if let Some(v) = options.to {
            parameters.insert("to".to_string(), v.to_string());
        }
        if let Some(v) = options.interval {
            parameters.insert("interval".to_string(), v.to_string());
        }
        self.client.get("/index-price", Some(parameters))
    }
}

pub struct IndexPriceOptions {
    pub from: Option<String>,
    pub to: Option<String>,
    pub interval: Option<String>,
}

impl IndexPriceOptions {
    pub fn new() -> Self {
        IndexPriceOptions {
            from: None,
            to: None,
            interval: None,
        }
    }

    pub fn from(mut self, from: impl Into<String>) -> Self {
        self.from = Some(from.into());
        self
    }

    pub fn to(mut self, to: impl Into<String>) -> Self {
        self.to = Some(to.into());
        self
    }

    pub fn interval(mut self, interval: impl Into<String>) -> Self {
        self.interval = Some(interval.into());
        self
    }
}

// --- Liquidation ---

#[derive(Clone)]
pub struct Liquidation {
    pub client: Client,
}

impl Datamaxi for Liquidation {
    fn new(api_key: String) -> Liquidation {
        let config = Config {
            base_url: None,
            api_key,
        };
        Liquidation {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Liquidation {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        Liquidation {
            client: Client::new(config),
        }
    }
}

impl Liquidation {
    /// Fetch recent liquidation events for a futures symbol on a given exchange, newest first.
    pub fn get(
        &self,
        exchange: impl Into<String>,
        symbol: impl Into<String>,
        options: LiquidationOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("symbol".to_string(), symbol.into());
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        self.client.get("/liquidation", Some(parameters))
    }

    /// Fetch most recent liquidation events across all futures symbols, newest first. Use together with the `/ws/v1/liquidation/feed` firehose for a live feed view.
    pub fn feed(&self, options: LiquidationFeedOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.base {
            parameters.insert("base".to_string(), v.to_string());
        }
        if let Some(v) = options.minVolumeUsd {
            parameters.insert("minVolumeUsd".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        self.client.get("/liquidation/feed", Some(parameters))
    }

    /// Aggregated long/short liquidation USD by (token, exchange) over a rolling window. Result is cached for ~10s. Sub-1h windows are not supported; use the WS feed for finer granularity.
    pub fn heatmap(&self, options: LiquidationHeatmapOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.window {
            parameters.insert("window".to_string(), v.to_string());
        }
        if let Some(v) = options.topN {
            parameters.insert("topN".to_string(), v.to_string());
        }
        self.client.get("/liquidation/heatmap", Some(parameters))
    }

    /// Coinglass-style liquidation map for one perpetual pair. Returns a price-grid breakdown of where leveraged positions would be liquidated, split by leverage tier (10x / 25x / 50x / 100x) and side (long below current price, short above). Built from current OI + last-24h candle entries + a fixed leverage-cohort prior. Read the `assumptions` field in the response for the modelling disclaimer. Cached server-side (~5s) so back-to-back polls are cheap.
    pub fn map(
        &self,
        base: impl Into<String>,
        options: LiquidationMapOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("base".to_string(), base.into());
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.quote {
            parameters.insert("quote".to_string(), v.to_string());
        }
        self.client.get("/liquidation/map", Some(parameters))
    }

    /// Aggregate liquidation stats (total, long/short split, count, venue count, biggest single event) over a 1h/4h/24h window. Backs the liquidation page KPI strip for windows the live feed buffer can't cover.
    pub fn stats(&self, options: LiquidationStatsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.window {
            parameters.insert("window".to_string(), v.to_string());
        }
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.minVolumeUsd {
            parameters.insert("minVolumeUsd".to_string(), v.to_string());
        }
        self.client.get("/liquidation/stats", Some(parameters))
    }

    /// Bucketed long / short liquidation USD over time for a single (base, quote) pair, joined with the futures-candle close as a reference price line. Long/short USD comes from `cex.liquidation` (Side='sell' = long position liquidated, 'buy' = short). Price comes from `candle.futures_1m` on the requested exchange — or Binance as the reference when none is specified. Cached ~30s server-side.
    pub fn symbol_history(
        &self,
        symbol: impl Into<String>,
        options: LiquidationSymbolHistoryOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("symbol".to_string(), symbol.into());
        if let Some(v) = options.quote {
            parameters.insert("quote".to_string(), v.to_string());
        }
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.interval {
            parameters.insert("interval".to_string(), v.to_string());
        }
        if let Some(v) = options.window {
            parameters.insert("window".to_string(), v.to_string());
        }
        self.client
            .get("/liquidation/symbol-history", Some(parameters))
    }
}

pub struct LiquidationOptions {
    pub limit: Option<i64>,
}

impl LiquidationOptions {
    pub fn new() -> Self {
        LiquidationOptions { limit: None }
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }
}

pub struct LiquidationFeedOptions {
    pub exchange: Option<String>,
    pub base: Option<String>,
    pub minVolumeUsd: Option<f64>,
    pub limit: Option<i64>,
}

impl LiquidationFeedOptions {
    pub fn new() -> Self {
        LiquidationFeedOptions {
            exchange: None,
            base: None,
            minVolumeUsd: None,
            limit: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn base(mut self, base: impl Into<String>) -> Self {
        self.base = Some(base.into());
        self
    }

    pub fn minVolumeUsd(mut self, minVolumeUsd: f64) -> Self {
        self.minVolumeUsd = Some(minVolumeUsd);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }
}

pub struct LiquidationHeatmapOptions {
    pub window: Option<String>,
    pub topN: Option<i64>,
}

impl LiquidationHeatmapOptions {
    pub fn new() -> Self {
        LiquidationHeatmapOptions {
            window: None,
            topN: None,
        }
    }

    pub fn window(mut self, window: impl Into<String>) -> Self {
        self.window = Some(window.into());
        self
    }

    pub fn topN(mut self, topN: i64) -> Self {
        self.topN = Some(topN);
        self
    }
}

pub struct LiquidationMapOptions {
    pub exchange: Option<String>,
    pub quote: Option<String>,
}

impl LiquidationMapOptions {
    pub fn new() -> Self {
        LiquidationMapOptions {
            exchange: None,
            quote: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn quote(mut self, quote: impl Into<String>) -> Self {
        self.quote = Some(quote.into());
        self
    }
}

pub struct LiquidationStatsOptions {
    pub window: Option<String>,
    pub exchange: Option<String>,
    pub minVolumeUsd: Option<f64>,
}

impl LiquidationStatsOptions {
    pub fn new() -> Self {
        LiquidationStatsOptions {
            window: None,
            exchange: None,
            minVolumeUsd: None,
        }
    }

    pub fn window(mut self, window: impl Into<String>) -> Self {
        self.window = Some(window.into());
        self
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn minVolumeUsd(mut self, minVolumeUsd: f64) -> Self {
        self.minVolumeUsd = Some(minVolumeUsd);
        self
    }
}

pub struct LiquidationSymbolHistoryOptions {
    pub quote: Option<String>,
    pub exchange: Option<String>,
    pub interval: Option<String>,
    pub window: Option<String>,
}

impl LiquidationSymbolHistoryOptions {
    pub fn new() -> Self {
        LiquidationSymbolHistoryOptions {
            quote: None,
            exchange: None,
            interval: None,
            window: None,
        }
    }

    pub fn quote(mut self, quote: impl Into<String>) -> Self {
        self.quote = Some(quote.into());
        self
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn interval(mut self, interval: impl Into<String>) -> Self {
        self.interval = Some(interval.into());
        self
    }

    pub fn window(mut self, window: impl Into<String>) -> Self {
        self.window = Some(window.into());
        self
    }
}

// --- Listing ---

#[derive(Clone)]
pub struct Listing {
    pub client: Client,
}

impl Datamaxi for Listing {
    fn new(api_key: String) -> Listing {
        let config = Config {
            base_url: None,
            api_key,
        };
        Listing {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Listing {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        Listing {
            client: Client::new(config),
        }
    }
}

impl Listing {
    /// Get historical token listings for Upbit and Bithumb for KRW market
    pub fn historical(&self, options: ListingsHistoricalOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.refresh {
            parameters.insert("refresh".to_string(), v.to_string());
        }
        self.client.get("/listings/historical", Some(parameters))
    }
}

pub struct ListingsHistoricalOptions {
    pub refresh: Option<bool>,
}

impl ListingsHistoricalOptions {
    pub fn new() -> Self {
        ListingsHistoricalOptions { refresh: None }
    }

    pub fn refresh(mut self, refresh: bool) -> Self {
        self.refresh = Some(refresh);
        self
    }
}

// --- MarginBorrow ---

#[derive(Clone)]
pub struct MarginBorrow {
    pub client: Client,
}

impl Datamaxi for MarginBorrow {
    fn new(api_key: String) -> MarginBorrow {
        let config = Config {
            base_url: None,
            api_key,
        };
        MarginBorrow {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> MarginBorrow {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        MarginBorrow {
            client: Client::new(config),
        }
    }
}

impl MarginBorrow {
    /// Get the margin borrow data.
    pub fn get(&self, asset: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("asset".to_string(), asset.into());
        self.client.get("/margin-borrow", Some(parameters))
    }
}

// --- NaverTrend ---

#[derive(Clone)]
pub struct NaverTrend {
    pub client: Client,
}

impl Datamaxi for NaverTrend {
    fn new(api_key: String) -> NaverTrend {
        let config = Config {
            base_url: None,
            api_key,
        };
        NaverTrend {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> NaverTrend {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        NaverTrend {
            client: Client::new(config),
        }
    }
}

impl NaverTrend {
    /// Get Naver trend data with a daily frequency for a project that is associated with a given [symbol](./symbols). The values in response are normalized into a range from 0 to 100, where 0 corresponds to a minimum interest, and 100 corresponds to a maximum interest of users in Naver search engine.
    pub fn get(&self, symbol: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("symbol".to_string(), symbol.into());
        self.client.get("/naver-trend", Some(parameters))
    }

    /// Get crypto symbols that are accepted by [Naver trend endpoint](./trend).
    pub fn symbols(&self) -> Result<serde_json::Value> {
        self.client.get("/naver-trend/symbols", None)
    }
}

// --- OpenInterest ---

#[derive(Clone)]
pub struct OpenInterest {
    pub client: Client,
}

impl Datamaxi for OpenInterest {
    fn new(api_key: String) -> OpenInterest {
        let config = Config {
            base_url: None,
            api_key,
        };
        OpenInterest {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> OpenInterest {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        OpenInterest {
            client: Client::new(config),
        }
    }
}

impl OpenInterest {
    /// Fetch the most recent Open Interest snapshot for a futures symbol on a given exchange.
    pub fn get(
        &self,
        exchange: impl Into<String>,
        symbol: impl Into<String>,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("symbol".to_string(), symbol.into());
        self.client.get("/open-interest", Some(parameters))
    }

    /// Historical Open Interest time series for a single token, broken down per exchange and aggregated to a fixed bucket (avg within bucket). The default lookback depends on the requested interval — 7 days for 1h, 30 days for 4h, 1 year for 1d — so callers don't have to hand-tune `from`/`to` for typical queries. The response also includes token metadata (icon, symbol, name) so a single call paints the whole header strip.
    pub fn history_aggregated(
        &self,
        token_id: impl Into<String>,
        options: OpenInterestHistoryAggregatedOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("token_id".to_string(), token_id.into());
        if let Some(v) = options.interval {
            parameters.insert("interval".to_string(), v.to_string());
        }
        if let Some(v) = options.from {
            parameters.insert("from".to_string(), v.to_string());
        }
        if let Some(v) = options.to {
            parameters.insert("to".to_string(), v.to_string());
        }
        self.client
            .get("/open-interest/history-aggregated", Some(parameters))
    }

    /// Fetch latest Open Interest snapshots across exchanges/symbols. Optionally filter by `exchange`. Results are sorted by `openInterestUsd` descending (null values last).
    pub fn list(&self, options: OpenInterestListOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        self.client.get("/open-interest/list", Some(parameters))
    }

    /// Paginated token × exchange Open Interest matrix. For each base asset we list the per-exchange notional OI in USD (when a venue carries the token) and `null` when it doesn't trade there. The matrix is sortable by any exchange column and searchable by base symbol — same shape the DataMaxi+ dashboard uses on `/open-interest`. Cached snapshot rebuilds every few seconds, so back-to-back requests are cheap.
    pub fn overview(&self, options: OpenInterestOverviewOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.key {
            parameters.insert("key".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        if let Some(v) = options.query {
            parameters.insert("query".to_string(), v.to_string());
        }
        self.client.get("/open-interest/overview", Some(parameters))
    }

    /// Top-line aggregates over the current Open Interest snapshot — total OI USD, top tokens by OI, top exchanges by OI, and the count of venues currently reporting any base. Powers the OI page's KPI strip and breakdown card without forcing the caller to fetch the full token list.
    pub fn summary(&self, options: OpenInterestSummaryOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.topN {
            parameters.insert("topN".to_string(), v.to_string());
        }
        self.client.get("/open-interest/summary", Some(parameters))
    }
}

pub struct OpenInterestHistoryAggregatedOptions {
    pub interval: Option<String>,
    pub from: Option<i64>,
    pub to: Option<i64>,
}

impl OpenInterestHistoryAggregatedOptions {
    pub fn new() -> Self {
        OpenInterestHistoryAggregatedOptions {
            interval: None,
            from: None,
            to: None,
        }
    }

    pub fn interval(mut self, interval: impl Into<String>) -> Self {
        self.interval = Some(interval.into());
        self
    }

    pub fn from(mut self, from: i64) -> Self {
        self.from = Some(from);
        self
    }

    pub fn to(mut self, to: i64) -> Self {
        self.to = Some(to);
        self
    }
}

pub struct OpenInterestListOptions {
    pub exchange: Option<String>,
}

impl OpenInterestListOptions {
    pub fn new() -> Self {
        OpenInterestListOptions { exchange: None }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }
}

pub struct OpenInterestOverviewOptions {
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub key: Option<String>,
    pub sort: Option<String>,
    pub query: Option<String>,
}

impl OpenInterestOverviewOptions {
    pub fn new() -> Self {
        OpenInterestOverviewOptions {
            page: None,
            limit: None,
            key: None,
            sort: None,
            query: None,
        }
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn key(mut self, key: impl Into<String>) -> Self {
        self.key = Some(key.into());
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }

    pub fn query(mut self, query: impl Into<String>) -> Self {
        self.query = Some(query.into());
        self
    }
}

pub struct OpenInterestSummaryOptions {
    pub topN: Option<i64>,
}

impl OpenInterestSummaryOptions {
    pub fn new() -> Self {
        OpenInterestSummaryOptions { topN: None }
    }

    pub fn topN(mut self, topN: i64) -> Self {
        self.topN = Some(topN);
        self
    }
}

// --- Premium ---

#[derive(Clone)]
pub struct Premium {
    pub client: Client,
}

impl Datamaxi for Premium {
    fn new(api_key: String) -> Premium {
        let config = Config {
            base_url: None,
            api_key,
        };
        Premium {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Premium {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        Premium {
            client: Client::new(config),
        }
    }
}

impl Premium {
    /// Returns the sorted list of categorical token tags currently indexed for the premium table filter. Updated on the aggregator's tagstate reload cadence.
    pub fn tags(&self) -> Result<serde_json::Value> {
        self.client.get("/front/premium/tags", None)
    }

    /// Get real-time premium (price difference) data across exchanges.
    pub fn get(&self, options: PremiumOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.source_exchange {
            parameters.insert("source_exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.target_exchange {
            parameters.insert("target_exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.asset {
            parameters.insert("asset".to_string(), v.to_string());
        }
        if let Some(v) = options.source_quote {
            parameters.insert("source_quote".to_string(), v.to_string());
        }
        if let Some(v) = options.target_quote {
            parameters.insert("target_quote".to_string(), v.to_string());
        }
        if let Some(v) = options.source_market {
            parameters.insert("source_market".to_string(), v.to_string());
        }
        if let Some(v) = options.target_market {
            parameters.insert("target_market".to_string(), v.to_string());
        }
        if let Some(v) = options.premium_type {
            parameters.insert("premium_type".to_string(), v.to_string());
        }
        if let Some(v) = options.currency {
            parameters.insert("currency".to_string(), v.to_string());
        }
        if let Some(v) = options.conversion_base {
            parameters.insert("conversion_base".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        if let Some(v) = options.key {
            parameters.insert("key".to_string(), v.to_string());
        }
        if let Some(v) = options.query {
            parameters.insert("query".to_string(), v.to_string());
        }
        if let Some(v) = options.only_transferable {
            parameters.insert("only_transferable".to_string(), v.to_string());
        }
        if let Some(v) = options.network {
            parameters.insert("network".to_string(), v.to_string());
        }
        if let Some(v) = options.min_sv {
            parameters.insert("min_sv".to_string(), v.to_string());
        }
        if let Some(v) = options.min_tv {
            parameters.insert("min_tv".to_string(), v.to_string());
        }
        self.client.get("/premium", Some(parameters))
    }

    /// Get supported source exchanges for premium data.
    pub fn exchanges(&self) -> Result<serde_json::Value> {
        self.client.get("/premium/exchanges", None)
    }
}

pub struct PremiumOptions {
    pub source_exchange: Option<String>,
    pub target_exchange: Option<String>,
    pub asset: Option<String>,
    pub source_quote: Option<String>,
    pub target_quote: Option<String>,
    pub source_market: Option<String>,
    pub target_market: Option<String>,
    pub premium_type: Option<String>,
    pub currency: Option<String>,
    pub conversion_base: Option<String>,
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub sort: Option<String>,
    pub key: Option<String>,
    pub query: Option<String>,
    pub only_transferable: Option<bool>,
    pub network: Option<String>,
    pub min_sv: Option<f64>,
    pub min_tv: Option<f64>,
}

impl PremiumOptions {
    pub fn new() -> Self {
        PremiumOptions {
            source_exchange: None,
            target_exchange: None,
            asset: None,
            source_quote: None,
            target_quote: None,
            source_market: None,
            target_market: None,
            premium_type: None,
            currency: None,
            conversion_base: None,
            page: None,
            limit: None,
            sort: None,
            key: None,
            query: None,
            only_transferable: None,
            network: None,
            min_sv: None,
            min_tv: None,
        }
    }

    pub fn source_exchange(mut self, source_exchange: impl Into<String>) -> Self {
        self.source_exchange = Some(source_exchange.into());
        self
    }

    pub fn target_exchange(mut self, target_exchange: impl Into<String>) -> Self {
        self.target_exchange = Some(target_exchange.into());
        self
    }

    pub fn asset(mut self, asset: impl Into<String>) -> Self {
        self.asset = Some(asset.into());
        self
    }

    pub fn source_quote(mut self, source_quote: impl Into<String>) -> Self {
        self.source_quote = Some(source_quote.into());
        self
    }

    pub fn target_quote(mut self, target_quote: impl Into<String>) -> Self {
        self.target_quote = Some(target_quote.into());
        self
    }

    pub fn source_market(mut self, source_market: impl Into<String>) -> Self {
        self.source_market = Some(source_market.into());
        self
    }

    pub fn target_market(mut self, target_market: impl Into<String>) -> Self {
        self.target_market = Some(target_market.into());
        self
    }

    pub fn premium_type(mut self, premium_type: impl Into<String>) -> Self {
        self.premium_type = Some(premium_type.into());
        self
    }

    pub fn currency(mut self, currency: impl Into<String>) -> Self {
        self.currency = Some(currency.into());
        self
    }

    pub fn conversion_base(mut self, conversion_base: impl Into<String>) -> Self {
        self.conversion_base = Some(conversion_base.into());
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }

    pub fn key(mut self, key: impl Into<String>) -> Self {
        self.key = Some(key.into());
        self
    }

    pub fn query(mut self, query: impl Into<String>) -> Self {
        self.query = Some(query.into());
        self
    }

    pub fn only_transferable(mut self, only_transferable: bool) -> Self {
        self.only_transferable = Some(only_transferable);
        self
    }

    pub fn network(mut self, network: impl Into<String>) -> Self {
        self.network = Some(network.into());
        self
    }

    pub fn min_sv(mut self, min_sv: f64) -> Self {
        self.min_sv = Some(min_sv);
        self
    }

    pub fn min_tv(mut self, min_tv: f64) -> Self {
        self.min_tv = Some(min_tv);
        self
    }
}

// --- Telegram ---

#[derive(Clone)]
pub struct Telegram {
    pub client: Client,
}

impl Datamaxi for Telegram {
    fn new(api_key: String) -> Telegram {
        let config = Config {
            base_url: None,
            api_key,
        };
        Telegram {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Telegram {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        Telegram {
            client: Client::new(config),
        }
    }
}

impl Telegram {
    /// Get Telegram channels
    pub fn channels(&self, options: TelegramChannelsOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.category {
            parameters.insert("category".to_string(), v.to_string());
        }
        if let Some(v) = options.key {
            parameters.insert("key".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        self.client.get("/telegram/channels", Some(parameters))
    }

    /// Get Telegram messages.
    pub fn messages(&self, options: TelegramMessagesOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.channel {
            parameters.insert("channel".to_string(), v.to_string());
        }
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.key {
            parameters.insert("key".to_string(), v.to_string());
        }
        if let Some(v) = options.sort {
            parameters.insert("sort".to_string(), v.to_string());
        }
        if let Some(v) = options.category {
            parameters.insert("category".to_string(), v.to_string());
        }
        if let Some(v) = options.search_query {
            parameters.insert("search_query".to_string(), v.to_string());
        }
        self.client.get("/telegram/messages", Some(parameters))
    }
}

pub struct TelegramChannelsOptions {
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub category: Option<String>,
    pub key: Option<String>,
    pub sort: Option<String>,
}

impl TelegramChannelsOptions {
    pub fn new() -> Self {
        TelegramChannelsOptions {
            page: None,
            limit: None,
            category: None,
            key: None,
            sort: None,
        }
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn category(mut self, category: impl Into<String>) -> Self {
        self.category = Some(category.into());
        self
    }

    pub fn key(mut self, key: impl Into<String>) -> Self {
        self.key = Some(key.into());
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }
}

pub struct TelegramMessagesOptions {
    pub channel: Option<String>,
    pub page: Option<i64>,
    pub limit: Option<i64>,
    pub key: Option<String>,
    pub sort: Option<String>,
    pub category: Option<String>,
    pub search_query: Option<String>,
}

impl TelegramMessagesOptions {
    pub fn new() -> Self {
        TelegramMessagesOptions {
            channel: None,
            page: None,
            limit: None,
            key: None,
            sort: None,
            category: None,
            search_query: None,
        }
    }

    pub fn channel(mut self, channel: impl Into<String>) -> Self {
        self.channel = Some(channel.into());
        self
    }

    pub fn page(mut self, page: i64) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: i64) -> Self {
        self.limit = Some(limit);
        self
    }

    pub fn key(mut self, key: impl Into<String>) -> Self {
        self.key = Some(key.into());
        self
    }

    pub fn sort(mut self, sort: impl Into<String>) -> Self {
        self.sort = Some(sort.into());
        self
    }

    pub fn category(mut self, category: impl Into<String>) -> Self {
        self.category = Some(category.into());
        self
    }

    pub fn search_query(mut self, search_query: impl Into<String>) -> Self {
        self.search_query = Some(search_query.into());
        self
    }
}

// --- Ticker ---

#[derive(Clone)]
pub struct Ticker {
    pub client: Client,
}

impl Datamaxi for Ticker {
    fn new(api_key: String) -> Ticker {
        let config = Config {
            base_url: None,
            api_key,
        };
        Ticker {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Ticker {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        Ticker {
            client: Client::new(config),
        }
    }
}

impl Ticker {
    /// Fetch the latest ticker for symbol from given exchange.
    pub fn get(
        &self,
        exchange: impl Into<String>,
        symbol: impl Into<String>,
        options: TickerOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        parameters.insert("symbol".to_string(), symbol.into());
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        if let Some(v) = options.currency {
            parameters.insert("currency".to_string(), v.to_string());
        }
        if let Some(v) = options.conversion_base {
            parameters.insert("conversion_base".to_string(), v.to_string());
        }
        self.client.get("/ticker", Some(parameters))
    }

    /// Get supported exchanges accepted by `/api/v1/ticker` endpoint.
    pub fn exchanges(&self, options: TickerExchangesOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        self.client.get("/ticker/exchanges", Some(parameters))
    }

    /// Get supported symbols accepted by `/api/v1/ticker` endpoint.
    pub fn symbols(
        &self,
        exchange: impl Into<String>,
        options: TickerSymbolsOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        if let Some(v) = options.market {
            parameters.insert("market".to_string(), v.to_string());
        }
        self.client.get("/ticker/symbols", Some(parameters))
    }
}

pub struct TickerOptions {
    pub market: Option<String>,
    pub currency: Option<String>,
    pub conversion_base: Option<String>,
}

impl TickerOptions {
    pub fn new() -> Self {
        TickerOptions {
            market: None,
            currency: None,
            conversion_base: None,
        }
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }

    pub fn currency(mut self, currency: impl Into<String>) -> Self {
        self.currency = Some(currency.into());
        self
    }

    pub fn conversion_base(mut self, conversion_base: impl Into<String>) -> Self {
        self.conversion_base = Some(conversion_base.into());
        self
    }
}

pub struct TickerExchangesOptions {
    pub market: Option<String>,
}

impl TickerExchangesOptions {
    pub fn new() -> Self {
        TickerExchangesOptions { market: None }
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }
}

pub struct TickerSymbolsOptions {
    pub market: Option<String>,
}

impl TickerSymbolsOptions {
    pub fn new() -> Self {
        TickerSymbolsOptions { market: None }
    }

    pub fn market(mut self, market: impl Into<String>) -> Self {
        self.market = Some(market.into());
        self
    }
}

// --- Token ---

#[derive(Clone)]
pub struct Token {
    pub client: Client,
}

impl Datamaxi for Token {
    fn new(api_key: String) -> Token {
        let config = Config {
            base_url: None,
            api_key,
        };
        Token {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> Token {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        Token {
            client: Client::new(config),
        }
    }
}

impl Token {
    /// Fetch latest token updates
    pub fn updates(&self, options: CexTokenUpdatesOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.page {
            parameters.insert("page".to_string(), v.to_string());
        }
        if let Some(v) = options.limit {
            parameters.insert("limit".to_string(), v.to_string());
        }
        if let Some(v) = options.r#type {
            parameters.insert("type".to_string(), v.to_string());
        }
        self.client.get("/cex/token/updates", Some(parameters))
    }
}

pub struct CexTokenUpdatesOptions {
    pub page: Option<String>,
    pub limit: Option<String>,
    pub r#type: Option<String>,
}

impl CexTokenUpdatesOptions {
    pub fn new() -> Self {
        CexTokenUpdatesOptions {
            page: None,
            limit: None,
            r#type: None,
        }
    }

    pub fn page(mut self, page: impl Into<String>) -> Self {
        self.page = Some(page.into());
        self
    }

    pub fn limit(mut self, limit: impl Into<String>) -> Self {
        self.limit = Some(limit.into());
        self
    }

    pub fn r#type(mut self, r#type: impl Into<String>) -> Self {
        self.r#type = Some(r#type.into());
        self
    }
}

// --- TradingFees ---

#[derive(Clone)]
pub struct TradingFees {
    pub client: Client,
}

impl Datamaxi for TradingFees {
    fn new(api_key: String) -> TradingFees {
        let config = Config {
            base_url: None,
            api_key,
        };
        TradingFees {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> TradingFees {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        TradingFees {
            client: Client::new(config),
        }
    }
}

impl TradingFees {
    /// Get trading fees.
    pub fn fees(&self, options: CexFeesOptions) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        if let Some(v) = options.symbol {
            parameters.insert("symbol".to_string(), v.to_string());
        }
        self.client.get("/cex/fees", Some(parameters))
    }

    /// Get supported exchanges accepted by `/api/v1/trading-fees` endpoint.
    pub fn exchanges(&self) -> Result<serde_json::Value> {
        self.client.get("/cex/fees/exchanges", None)
    }

    /// Get supported symbols accepted by `/api/v1/trading-fees` endpoint.
    pub fn symbols(&self, exchange: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        self.client.get("/cex/fees/symbols", Some(parameters))
    }
}

pub struct CexFeesOptions {
    pub exchange: Option<String>,
    pub symbol: Option<String>,
}

impl CexFeesOptions {
    pub fn new() -> Self {
        CexFeesOptions {
            exchange: None,
            symbol: None,
        }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }

    pub fn symbol(mut self, symbol: impl Into<String>) -> Self {
        self.symbol = Some(symbol.into());
        self
    }
}

// --- WalletStatus ---

#[derive(Clone)]
pub struct WalletStatus {
    pub client: Client,
}

impl Datamaxi for WalletStatus {
    fn new(api_key: String) -> WalletStatus {
        let config = Config {
            base_url: None,
            api_key,
        };
        WalletStatus {
            client: Client::new(config),
        }
    }
    fn new_with_base_url(api_key: String, base_url: String) -> WalletStatus {
        let config = Config {
            base_url: Some(base_url),
            api_key,
        };
        WalletStatus {
            client: Client::new(config),
        }
    }
}

impl WalletStatus {
    /// Get the latest wallet status for asset from given exchange.
    pub fn get(
        &self,
        asset: impl Into<String>,
        options: WalletStatusOptions,
    ) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("asset".to_string(), asset.into());
        if let Some(v) = options.exchange {
            parameters.insert("exchange".to_string(), v.to_string());
        }
        self.client.get("/wallet-status", Some(parameters))
    }

    /// Get assets accepted by `/api/v1/wallet-status` endpoint.
    pub fn assets(&self, exchange: impl Into<String>) -> Result<serde_json::Value> {
        let mut parameters = HashMap::new();
        parameters.insert("exchange".to_string(), exchange.into());
        self.client.get("/wallet-status/assets", Some(parameters))
    }

    /// Get exchanges accepted by `/api/v1/wallet-status` endpoint.
    pub fn exchanges(&self) -> Result<serde_json::Value> {
        self.client.get("/wallet-status/exchanges", None)
    }
}

pub struct WalletStatusOptions {
    pub exchange: Option<String>,
}

impl WalletStatusOptions {
    pub fn new() -> Self {
        WalletStatusOptions { exchange: None }
    }

    pub fn exchange(mut self, exchange: impl Into<String>) -> Self {
        self.exchange = Some(exchange.into());
        self
    }
}
